// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTUfkI7rHyM6RVE3IpBHzi6XpaoMfTVTc',
    appId: '1:1004920315658:web:93eb9fc5e95ac0bdc724f3',
    messagingSenderId: '1004920315658',
    projectId: 'capstone-final-aec4a',
    authDomain: 'capstone-final-aec4a.firebaseapp.com',
    storageBucket: 'capstone-final-aec4a.appspot.com',
    measurementId: 'G-CDVG3TRR5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu6DgAKdeUGeKnAwjHMW4okIJamFCj9Qk',
    appId: '1:1004920315658:android:fc115c25528b1f0dc724f3',
    messagingSenderId: '1004920315658',
    projectId: 'capstone-final-aec4a',
    storageBucket: 'capstone-final-aec4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnEEuMFRAcOdvp7RQzgHyqU46O1QybFag',
    appId: '1:1004920315658:ios:621c649345832825c724f3',
    messagingSenderId: '1004920315658',
    projectId: 'capstone-final-aec4a',
    storageBucket: 'capstone-final-aec4a.appspot.com',
    iosClientId: '1004920315658-og52pg8h14jokgkcilk2f7jvql0k4tv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnEEuMFRAcOdvp7RQzgHyqU46O1QybFag',
    appId: '1:1004920315658:ios:621c649345832825c724f3',
    messagingSenderId: '1004920315658',
    projectId: 'capstone-final-aec4a',
    storageBucket: 'capstone-final-aec4a.appspot.com',
    iosClientId: '1004920315658-og52pg8h14jokgkcilk2f7jvql0k4tv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );
}
