// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADidG5W6G42S2NM22G2pP9CDQq9SjqG2A',
    appId: '1:1096984138882:web:c28dfea2356a6efeaed09b',
    messagingSenderId: '1096984138882',
    projectId: 'talal814-auth-cap',
    authDomain: 'talal814-auth-cap.firebaseapp.com',
    databaseURL: 'https://talal814-auth-cap-default-rtdb.firebaseio.com',
    storageBucket: 'talal814-auth-cap.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwcBJaNx5G6mBjjPHpqCpG3VCJzG8uHl0',
    appId: '1:1096984138882:android:86862b9e302ba41faed09b',
    messagingSenderId: '1096984138882',
    projectId: 'talal814-auth-cap',
    databaseURL: 'https://talal814-auth-cap-default-rtdb.firebaseio.com',
    storageBucket: 'talal814-auth-cap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByLy7OHA4tMmVTo6QbzfPjp816SIIc6UU',
    appId: '1:1096984138882:ios:7529d18c98a53501aed09b',
    messagingSenderId: '1096984138882',
    projectId: 'talal814-auth-cap',
    databaseURL: 'https://talal814-auth-cap-default-rtdb.firebaseio.com',
    storageBucket: 'talal814-auth-cap.appspot.com',
    androidClientId: '1096984138882-6optr2350tec1oi8hmi2dienbbfgg8lb.apps.googleusercontent.com',
    iosClientId: '1096984138882-3mqcejc1v25o3tgtevenffdcn0jtddjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByLy7OHA4tMmVTo6QbzfPjp816SIIc6UU',
    appId: '1:1096984138882:ios:7529d18c98a53501aed09b',
    messagingSenderId: '1096984138882',
    projectId: 'talal814-auth-cap',
    databaseURL: 'https://talal814-auth-cap-default-rtdb.firebaseio.com',
    storageBucket: 'talal814-auth-cap.appspot.com',
    androidClientId: '1096984138882-6optr2350tec1oi8hmi2dienbbfgg8lb.apps.googleusercontent.com',
    iosClientId: '1096984138882-3mqcejc1v25o3tgtevenffdcn0jtddjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );
}
