// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEMgTEUxh5Fl80gVH6mBbJvMBkLRbeySM',
    appId: '1:19720031603:web:bfc7acfa0cb84db7f00906',
    messagingSenderId: '19720031603',
    projectId: 'caps-f938b',
    authDomain: 'caps-f938b.firebaseapp.com',
    storageBucket: 'caps-f938b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlvshUQ6rwPQgUU8fN4C12KvZE3oRAyGg',
    appId: '1:19720031603:android:5ba1b83d37ad4e79f00906',
    messagingSenderId: '19720031603',
    projectId: 'caps-f938b',
    storageBucket: 'caps-f938b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1DnjRfA8sc5hv0GQzkxJGPapwfNw0hxE',
    appId: '1:19720031603:ios:a0cbd57884ae27eaf00906',
    messagingSenderId: '19720031603',
    projectId: 'caps-f938b',
    storageBucket: 'caps-f938b.appspot.com',
    iosClientId: '19720031603-qg27p7rjfcnm19r2ag4gnutt4qsspia4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1DnjRfA8sc5hv0GQzkxJGPapwfNw0hxE',
    appId: '1:19720031603:ios:a0cbd57884ae27eaf00906',
    messagingSenderId: '19720031603',
    projectId: 'caps-f938b',
    storageBucket: 'caps-f938b.appspot.com',
    iosClientId: '19720031603-qg27p7rjfcnm19r2ag4gnutt4qsspia4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );
}
